### ISSUE TITLE
Yes-or-no emacs lisp bypass

### ISSUE THREAD

**Issue by doprdele** [IQSS/IQSS.emacs#14]
Hi Ista,

I was wondering if you could patch such that the (yes-no) functions are no longer used in init.el. If you don't have time, I could submit this patch for your approval.

I want to bake this into a docker image and use ```emacs --script``` to pre-compile all the functions, but, it still asks for interactive acceptance. 

Do you have a better way I might go about this other than patching?

Best,
Evan

**Comment by izahn** [comment]
Evan, I'm so sorry for not replying until now. In general, installing things without the permission of the user is not something I'm comfortable with, but it does make sense in the case of building a docker image. I'm happy to accept patches that make this easier, while preserving the confirmation by default.

________________________________

**Comment by whorka** [comment]
Hi Ista,

I submitted a patch which allows the automation of emacs startup while preserving the default prompting behavior.

Please review https://github.com/IQSS/IQSS.emacs/pull/15

I also updated `init.org` but did not re-generate `init.html` since my version of pandoc generated very different output.

Regards,
 -Bill
