### ISSUE TITLE
make 2nd compile request abort 1st

### ISSUE THREAD

**Issue by thegaryking** [IQSS/IQSS.emacs#5]
c-c, c-a compiles.  if while waiting for it to compile you see something else to change, change it, save, and hit c-c, c-a again, bad stuff happens.  a better behavior, after hitting c-c, c-a whenever compiling is happening, would be for it to abort the first compile automatically (without asking) and to restart it.

**Comment by izahn** [comment]
I'm not sure if something changed since this ticket was opened. Currently in this situation Emacs prompts you asking if you want to kill the currently running process before starting a new one. I think that is pretty reasonable, and I'm inclined to leave it as it is. I did add something so that `C-g` will also cancel any currently running jobs.

I'm closing this now, but please do re-open if there is still something here that needs to be improved.
