### ISSUE TITLE
unit tests

### ISSUE THREAD

**Issue by thegaryking** [IQSS/IQSS.emacs#9]
how about we eat our own dog food and create a set of unit tests that get run every time we are about to push a new version to git?

**Comment by izahn** [comment]
Since we don't implement any features it's hard to say what exactly we would test. Basically all the code in this repository does is download and run other people's code (in the form of Emacs packages). It doesn't seem reasonable to try to test the code in all the packages we use -- that is properly a job for the package authors. 

I'm closing this for now since I don't see how to translate it into an action we should take. Please do re-open if you have a specific suggestion for what and how we should test.
